<a href="https://colab.research.google.com/github/Sandyjiit/Machine-learning/blob/main/Wine_classification_by_KNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Here,we have different attributes to classify the wine class


In [2]:
#liabraries imported
import numpy as np
import pandas as pd


In [4]:
pip install sklearn

In [6]:
#import winne daaaaaata from sklearn library
from sklearn import datasets

#LOAD DATA
wine=datasets.load_wine()


In [7]:
 #name of the features
 print(wine.feature_names)

['alcohol', 'malic_acid', 'ash', 'alcalinity_of_ash', 'magnesium', 'total_phenols', 'flavanoids', 'nonflavanoid_phenols', 'proanthocyanins', 'color_intensity', 'hue', 'od280/od315_of_diluted_wines', 'proline']


In [9]:
#target names
print(wine.target_names)

['class_0' 'class_1' 'class_2']


In [11]:
#first five record of dataset
print(wine.data[0:5])

[[1.423e+01 1.710e+00 2.430e+00 1.560e+01 1.270e+02 2.800e+00 3.060e+00
  2.800e-01 2.290e+00 5.640e+00 1.040e+00 3.920e+00 1.065e+03]
 [1.320e+01 1.780e+00 2.140e+00 1.120e+01 1.000e+02 2.650e+00 2.760e+00
  2.600e-01 1.280e+00 4.380e+00 1.050e+00 3.400e+00 1.050e+03]
 [1.316e+01 2.360e+00 2.670e+00 1.860e+01 1.010e+02 2.800e+00 3.240e+00
  3.000e-01 2.810e+00 5.680e+00 1.030e+00 3.170e+00 1.185e+03]
 [1.437e+01 1.950e+00 2.500e+00 1.680e+01 1.130e+02 3.850e+00 3.490e+00
  2.400e-01 2.180e+00 7.800e+00 8.600e-01 3.450e+00 1.480e+03]
 [1.324e+01 2.590e+00 2.870e+00 2.100e+01 1.180e+02 2.800e+00 2.690e+00
  3.900e-01 1.820e+00 4.320e+00 1.040e+00 2.930e+00 7.350e+02]]


In [12]:
print(wine.target)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]


In [22]:
#splitting the data
from sklearn.model_selection import train_test_split


#data split : 28:62 :: test::train
X_train,X_test,Y_train,Y_test=train_test_split(wine.data,wine.target,test_size=.28)

In [23]:
len(wine.data)

178

In [24]:
len(wine.target)

178

**KNN MODEL BUILDING**

In [25]:
    from  sklearn.neighbors import KNeighborsClassifier

    
    

**CREATING A KNN CLASSIFIER**

In [47]:
 #k=5
 knn=KNeighborsClassifier(n_neighbors=5)

In [48]:
#MODEL TRAINING 
knn.fit(X_train,Y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=9, p=2,
                     weights='uniform')

In [49]:
print(wine.target.shape)

(178,)


In [50]:
print(len(X_train))

128


In [51]:
print(len(Y_train))

128


**MODEL PREDICTION  for K=5**

In [52]:
Y_pred=knn.predict(X_test)

In [53]:
print(Y_pred[0:5])

[1 2 0 1 1]


In [54]:
print(Y_test[0:5])

[1 1 1 1 1]


In [57]:
print(Y_train[0:5])

[0 2 0 1 0]


In [58]:
#performance matrices
from sklearn.metrics import confusion_matrix

confusion_matrix(Y_test,Y_pred) #y(actual output) and y^(predicted output)

array([[12,  0,  0],
       [ 4, 15,  6],
       [ 4,  2,  7]])

In [60]:
#import sklearn matrics for accuracy
from sklearn import metrics

print("accuracy of model for k=5 is",metrics.accuracy_score(Y_test,Y_pred))

accuracy of model for k=5 is 0.68
